### ISSUE TITLE
gva per sector for scenarios 0, 1, 2 different order of magnitude to baseline

### ISSUE THREAD

**Issue by willu47** [nismod/arc-economics#2]
For example:

timestep | lad_uk_2016 | sectors | gva_per_sector | baseline | unplanned | new-cities
-- | -- | -- | -- | -- | -- | --
2015 | E06000001 | 2 | 13.812944 | 10824.195921 | 13.812944 | 13.812944
2015 | E08000017 | 28 | 471.836332 | 8772.237410 | 471.836332 | 471.836332
2015 | E07000084 | 8 | 7.565480 | 1437.441149 | 7.565480 | 7.565480
2015 | E08000017 | 27 | 264.779320 | 9523.968665 | 264.779320 | 264.779320
2015 | E07000084 | 9 | 0.385775 | 478.360871 | 0.385775 | 0.385775
2015 | E08000017 | 23 | 295.547540 | 10630.684871 | 295.547540 | 295.547540
2015 | E07000084 | 10 | 23.466302 | 6006.889354 | 23.466302 | 23.466302
2015 | E08000017 | 19 | 441.898150 | 7300.736982 | 441.898150 | 441.898150

**Comment by tomalrussell** [comment]
Closed by #3
